remote_theme: mmistakes/skinny-bones-jekyll

# Site wide configuration
title: "Northern Widget LLC"
description: "Open source for the outdoors"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: https://northernwidget.github.io
feed:
  path: atom.xml
